import numpy as np

stop_words = np.array([
    'please', 'thanks', 'thank', 'you', 'regards', 'best', 'hello', 'hi', 'dear', 'sincerely', 
    'contact', 'us', 'help', 'support', 'email', 'phone', 'number', 'customer', 'service', 
    'inquiry', 'request', 'response', 'reply', 'information', 'details', 'find', 'attached', 
    'document', 'form', 'message', 'call', 'issue', 'problem', 'question', 'concern', 'assistance', 
    'feedback', 'urgent', 'important', 'matter', 'follow', 'up', 'confirm', 'confirmation', 'need', 
    'needed', 'require', 'required', 'urgent', 'case', 'submit', 'submitted', 'date', 'time', 'week', 
    'month', 'year', 'day', 'received', 'receive', 'sent', 'send', 'sending', 'forward', 'requesting', 
    'requested', 'attached', 'attachment', 'attachments', 'related', 'issue', 'issues', 'team', 'company', 
    'company’s', 'business', 'team', 'organization', 'department', 'sales', 'billing', 'payment', 'invoice', 
    'reference', 'id', 'ticket', 'complaint', 'account', 'credentials', 'order', 'tracking', 'shipment', 
    'delivery', 'status', 'update', 'updated', 'updates', 'address', 'shipping', 'item', 'product', 
    'products', 'services', 'service', 'provider', 'team', 'business', 'action', 'actions', 'follow', 
    'via', 'regarding', 'concern', 'concerns', 'problem', 'problems', 'issue', 'issues', 'urgent', 'critical', 
    'alert', 'attention', 'emergency', 'immediate', 'request', 'requests', 'question', 'questions', 'inquiry', 
    'queries', 'inquiries', 'support', 'help', 'assistance', 'assisting', 'assist', 'contact', 'phone', 
    'number', 'numbers', 'reply', 'replies', 'respond', 'responded', 'responses', 'response', 'answer', 
    'answers', 'solved', 'solve', 'solution', 'solutions', 'fixed', 'fix', 'helped', 'resolve', 'resolved', 
    'resolving', 'action', 'actions', 'file', 'files', 'case', 'cases', 'claim', 'claims', 'status', 'statuses', 
    'email', 'emails', 'call', 'calls', 'calling', 'contacted', 'responding', 'please', 'thank', 'thanks', 
    'regards', 'best', 'sincerely', 'kind', 'appreciate', 'appreciation', 'your', 'ours', 'mine', 'reply', 
    'send', 'sending', 'forward', 'message', 'messages', 'communication', 'communicate', 'forwarded', 'cc', 
    'bcc', 'case', 'number', 'attached', 'documents', 'included', 'included', 'attached', 'files', 'forms', 
    'sent', 'send', 'sending', 'forwarded', 'issue', 'problem', 'concern', 'follow', 'follow-up', 'alert', 
    'escalate', 'escalated', 'action', 'actions', 'taken', 'outcome', 'solutions', 'resolved', 'responded', 
    'response', 'reply', 'solved', 'resolution', 'resolved', 'fix', 'issue', 'problem', 'solutions', 
    'assisting', 'assist', 'help', 'support', 'inquiry', 'contact', 'phone', 'email', 'address', 'request', 
    'requesting', 'question', 'answered', 'details', 'attachment', 'documents', 'response', 'answer', 
    'confirm', 'verification', 'confirmed', 'verify', 'confirming', 'sent', 'message', 'reply', 'forward', 
    'attention', 'address', 'phone', 'number', 'email', 'attached', 'attached', 'details', 'feedback', 
    'comment', 'comments', 'questions', 'issues', 'problem', 'assistance', 'help', 'helped', 'address', 
    'email', 'details', 'information', 'phone', 'attached', 'attached', 'included', 'included', 'comments', 
    'feedback', 'problem', 'resolved', 'response', 'answers', 'contacted', 'reached', 'called', 'phone', 
    'email', 'attached', 'attached', 'included', 'document', 'form', 'reply', 'replied', 'respond', 
    'responded', 'status', 'case', 'resolved', 'solved', 'solution', 'solutions', 'problem', 'answer', 
    'questions', 'resolved', 'fix', 'resolved', 'issue', 'solution', 'confirm', 'verify', 'verified', 
    'confirmed', 'response', 'address', 'email', 'phone', 'attached', 'form', 'sent', 'included', 
    'attached', 'confirmed', 'document', 'form', 'question', 'feedback', 'comments', 'issue', 'solved', 
    'solutions', 'follow', 'send', 'sent', 'forward', 'contacted', 'reached', 'help', 'issue', 'questions', 
    'sent', 'request', 'help', 'support', 'address', 'sent', 'document', 'email', 'sent', 'attached', 
    'request', 'document', 'issue', 'problem', 'help', 'forward', 'sent', 'reply', 'response', 'included', 
    'form', 'address', 'details', 'help', 'feedback', 'attached', 'response', 'email', 'support', 'solved', 
    'solution', 'follow', 'sent', 'address', 'questions', 'comments', 'reply', 'response', 'phone', 
    'number', 'attached', 'document', 'form', 'help', 'sent', 'included', 'confirmed', 'verified', 
    'document', 'sent', 'contact', 'help', 'email', 'response', 'sent', 'included', 'details', 'response', 
    'help', 'phone', 'attached', 'document', 'confirmed', 'attached', 'document', 'form', 'help', 
    'question', 'address', 'confirmed', 'sent', 'details', 'attached', 'help', 'response', 'comments', 
    'feedback', 'email', 'attached', 'response', 'included', 'sent', 'request', 'problem', 'support', 
    'solution', 'solved', 'attached', 'sent', 'included', 'document', 'form', 'phone', 'verified', 
    'sent', 'reply', 'response', 'questions', 'attached', 'help', 'included', 'sent', 'feedback', 
    'details', 'confirmed', 'verified', 'solution', 'problem', 'attached', 'sent', 'included', 'reply', 
    'response', 'question', 'feedback', 'attached', 'phone', 'email', 'help', 'sent', 'address', 
    'questions', 'support', 'included', 'document', 'verified', 'attached', 'sent', 'form', 'response'
])

print(stop_words)
